apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-postgres-api
  labels:
    app: fastapi-postgres-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-postgres-api
  template:
    metadata:
      labels:
        app: fastapi-postgres-api
    spec:
      containers:
      - name: fastapi-postgres-api
        image: ${YOUR_ALIYUN_REGISTRY}/fastapi-postgres-api:latest
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-postgres-api
spec:
  selector:
    app: fastapi-postgres-api
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fastapi-postgres-api-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: api.example.com  # 请替换为您的域名
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fastapi-postgres-api
            port:
              number: 80 